---
title: "🗓️ Week 04 - The Rocky Intertidal"
---
## 🌊 🦀 Tides for this week
```{r}
#| warning: false 
#| message: false
#| echo: false
#list.dirs("../../..")
source("../../../helpers/make_tideplot.R")
make_tideplot("2026-09-28")
```


This week we will focus on the Rocky Intertidal habitat. The Rocky intertidal is truly the workhorse ecosystem of marine ecology - particularly experimental ecology. Why? Zonation! We will spend a good chunk of the week talking about how the rocky intertidal has helped us develop paradigms relating to the balance of 

## 🌅 EARLY INTERTIDAL LAB!
Please see the [lab](./lab.qmd) page for this week. We will have lab EARLY - on Monday at 6am meeting at the Bayside parking lot. See the [lab](./lab.qmd) page for more.


## 👨‍🏫 Lecture Slides 

You can find the powerpoint file of the slides [here](http://files.celp-lab.org/biol311/lectures/06_rocky_intertidal.pptx). 

## ✍️ Coursework

For all readings, username is biol311 and password is marinebio!!

Please read [Menge and Branch 2000](https://files.celp-lab.org/biol311/readings/rocky_intertidal/ch09%20Menge%20&%20Branch%202001%20Marine%20Community%20Ecology%20Rocky%20intertidal%20communities.pdf) for Monday.

For paper discussion on Wednesday, read [...](...) and then fill out your weekly [reading Q&A](/assignments/reading_q_and_a.docx).


## 🧠🐛❓ Would you like to know more?

Read the classic [@connellInfluenceInterspecificCompetition1961](https://files.celp-lab.org/biol311/readings/rocky_intertidal/Connell%201961%20Ecology.pdf)

Read the classic [@paineFoodWebCompexity1966](https://files.celp-lab.org/biol311/readings/rocky_intertidal/Paine%201966%20Am.%20Nat.pdf)! Or, the extended remix of [@paineIntertidalCommunityStructure1974](https://files.celp-lab.org/biol311/readings/rocky_intertidal/Paine%201974%20Oecologia.pdf). Want to hear more of the story with respect fo facilitation? See [@laffertykevind.RevisitingPaines19662016](https://files.celp-lab.org/biol311/readings/rocky_intertidal/Paine-1966-Revisit.pdf)

Read the classic [@lubchencoPlantSpeciesDiversity1978](https://files.celp-lab.org/biol311/readings/rocky_intertidal/Lubchenco%201978%20Am%20Nat.pdf) on how snails shape biodiversity here in New England rockpools!

For one of the best reviews of rocky shores as the fruit-fly of experimental ecology, see [@hawkinsRockyShoresTractable2020](https://files.celp-lab.org/biol311/readings/rocky_intertidal/hawkins2020.pdf)

How do we put together a big theoretical understanding of the rocky intertidal? See [@mengeSpeciesDiversityGradients1976](https://files.celp-lab.org/biol311/readings/rocky_intertidal/MengeSutherland87AmNat.pdf) - and if you want that modified by thoughts about facilitation, see [@brunoInclusionFacilitationEcological2003](https://files.celp-lab.org/biol311/readings/rocky_intertidal/BrunoetalTREE2003.pdf)

Want an experimental test of the facilitation done by canopies in the rocky intertidal? See [@bertnessTestingRelativeContribution1999](https://files.celp-lab.org/biol311/readings/rocky_intertidal/Ecology%20-%201999%20-%20Bertness%20-%20TESTING%20THE%20RELATIVE%20CONTRIBUTION%20OF%20POSITIVE%20AND%20NEGATIVE%20INTERACTIONS%20IN%20ROCKY%20INTERTIDAL.pdf)

What about an alga creating a whole community unto itself? See [@brackenWholecommunityMutualismAssociated2007](https://files.celp-lab.org/biol311/readings/rocky_intertidal/Bracken%20et%20al%202007%20Ecology.pdf)

Would you like a broad biogeographic view of the rocky intertidal of the Gulf of Maine? See [@brysonBroadscaleGeographicVariation2014](https://files.celp-lab.org/biol311/readings/rocky_intertidal/Bryson_2014.pdf)

## 📚  References

::: {#refs}
:::
